name: Build & Pack

on:
  push:
    branches: [ "master" ]  # or "main" if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # If your project uses `npm run build` or `gulp build`, do that here:
      - name: Build project
        run: npm run build

      - name: Pack library
        run: npm pack

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: powerquery-parser-tarball
          path: '*.tgz'
